language: objective-c 
osx_image: xcode9.4
script:
  - set -o pipefail
  - xcodebuild clean test -workspace Colorspin.xcworkspace -scheme ColorspinDebug -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet | xcpretty -c
  - swiftlint