language: objective-c 
osx_image: xcode10.0
script:
  - set -o pipefail
  - xcodebuild clean test -workspace Colorspin.xcworkspace -scheme ColorspinDebug -destination "platform=iOS Simulator,name=iPhone 7,OS=12.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet | xcpretty -c
  - swiftlint